version: 1.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2019
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '%APPVEYOR_BUILD_VERSION%'
  assembly_file_version: '%APPVEYOR_BUILD_VERSION%'
  assembly_informational_version: '%APPVEYOR_BUILD_VERSION%'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '%APPVEYOR_BUILD_VERSION%'
  version_prefix: '%APPVEYOR_BUILD_VERSION%'
  package_version: '%APPVEYOR_BUILD_VERSION%'
  assembly_version: '%APPVEYOR_BUILD_VERSION%'
  file_version: '%APPVEYOR_BUILD_VERSION%'
  informational_version: '%APPVEYOR_BUILD_VERSION%'
before_build:
- cmd: nuget restore Spacearr.sln
build:
  verbosity: minimal
test_script:
- cmd: >-
    nuget install Appveyor.TestLogger -Version 2.0.0

    dotnet test Spacearr.Common.Tests\Spacearr.Common.Tests.csproj --configuration Release --no-build --test-adapter-path:. --logger:Appveyor

    dotnet test Spacearr.Core.Xamarin.Tests\Spacearr.Core.Xamarin.Tests.csproj --configuration Release --no-build --test-adapter-path:. --logger:Appveyor
artifacts:
- path: Spacearr.Android\bin\$(configuration)\*-Signed.apk
  name: Spacearr.Android v$(appveyor_build_version)
  type: zip
- path: Spacearr.UWP\AppPackages
  name: Spacearr.UWP v$(appveyor_build_version)
  type: zip
- path: Spacearr.Windows.Service.Setup\bin\$(configuration)
  name: Spacearr.Windows.Service v$(appveyor_build_version)
  type: zip
- path: Spacearr.WorkerService.Windows\bin\$(configuration)
  name: Spacearr.WorkerService.Windows v$(appveyor_build_version)
  type: zip
deploy:
- provider: GitHub
  auth_token:
    secure: UZlJS4I1Uhwz3+gT51KJTXF3jLAvdaH8UeS6NyZdxcN/qTQyanLmobxOk+psRlJ9
  on:
    branch: master