version: 1.0.0.{build}
skip_tags: true
pull_requests:
  do_not_increment_build_number: true
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.0.{build}"
  assembly_file_version: "{version}"
image: Visual Studio 2019
before_build:
- cmd: nuget restore Spacearr.sln
build:
  project: Spacearr.sln
  verbosity: minimal
artifacts:
- path: Spacearr.Windows.Service.Setup\bin\Debug\
  name: Spacearr.Windows.Service v$(appveyor_build_version)