version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    description: Run tests
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: msbuild -t:restore
      - run:
          name: "Run Spacearr Common Tests"
          command: dotnet.exe test Spacearr.Common.Tests/Spacearr.Common.Tests.csproj -v n --results-directory:test_coverage --collect:"Code Coverage"
      - run:
          name: "Run Spacearr Core Xamarin Tests"
          command: dotnet.exe test Spacearr.Core.Xamarin.Tests/Spacearr.Core.Xamarin.Tests.csproj -v n --results-directory:test_coverage --collect:"Code Coverage"
      - run:
          name: "Print Working Directory"
          command: pwd
      - store_artifacts:
          path: C:\Users\circleci\project\test_coverage
  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: msbuild -t:restore
      - run:
          name: "Build application"
          command: msbuild Spacearr.Windows.Service.Setup\Spacearr.Windows.Service.Setup.wixproj /p:Configuration="Release"
workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test