version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: msbuild nuget restore Spacearr.sln
      - run:
          name: "Build in release configuration"
          command: msbuild build --configuration Release